version: '3.3'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db  # Certifique-se de que o host corresponde ao nome do serviço do MySQL
      PMA_USER: ${MYSQL_USER}  # Opcional: Usuário para login no phpMyAdmin
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
volumes:
  my-db: