# Definir uma variável de ambiente para indicar o ambiente
###################
# UTILIZAR APENAS NO AMBIENTE DE DESENVOLVIMENTO
###################

FROM node:18-alpine As development
WORKDIR /usr/src/app

RUN chmod 777 /usr/src/app

COPY . .
COPY --chown=node:node package*.json ./

EXPOSE 3000
RUN npm ci
COPY --chown=node:node . .
USER node

CMD ["npm", "run", "start"]

