version: '3.3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.local
    env_file: .env
    ports:
      - "3000:3000"
  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8085:80"
    depends_on:
      - db
volumes:
  my-db: