name: Deploy to Staging
on:
  pull_request:
    branches: ['*']

jobs:
  executar_testes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run coverage
        run: npm run test:cov
      
      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e
